import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export type SidebarItem = {
  slug: string; // 'index' for the home page; otherwise the markdown filename without .md
  label: string;
  badge?: string;
};

export type SidebarSection = {
  title: string;
  items: SidebarItem[];
};

// The sidebar is generated by `scripts/sync.mjs` (runs before `astro dev` /
// `astro build`) and written to sidebar.generated.json. We read it with fs
// rather than `import ... from './sidebar.generated.json'` so a missing file
// (fresh checkout, before first sync) degrades to an empty sidebar instead of
// a build error. This module only runs server-side (imported by Layout.astro),
// so fs is available.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const generatedFile = path.join(__dirname, 'sidebar.generated.json');

function loadSidebar(): SidebarSection[] {
  try {
    if (!fs.existsSync(generatedFile)) return [];
    return JSON.parse(fs.readFileSync(generatedFile, 'utf8')) as SidebarSection[];
  } catch {
    return [];
  }
}

export const sidebarSections: SidebarSection[] = loadSidebar();
